TheBigDukan/Controllers/LogInController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheBigDukan.Models;

namespace TheBigDukan.Controllers
{
    public class LogInController : Controller
    {
        Entities1 db = new Entities1();

        public string FileName { get; private set; }

        // GET: LogIn
        [HttpGet]
        public ActionResult LogInAction()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogInAction(Registration myLoginModel)
            
        {
            
            ActionResult myaction = RedirectToAction("VenderActionIndex", "Vendor");
            string id = myLoginModel.email;
            string pass = myLoginModel.password;
            if (id != null && pass != null)
            {
                try
                {
                    Registration regform = db.Registrations.Single(w => w.email == id && w.password == pass);
                  //  Response.Write(regform.name);
                    if (ModelState.IsValid)
                    {
                        if (regform == null)
                        {
                            
                           // myLoginModel.ErrorMsg = "not found";
                            myaction = View(myLoginModel);
                        }
                        else
                        {
                            SignUpModel mod = new SignUpModel(regform);


                             myaction = RedirectToAction("VenderActionIndex", "Vendor",mod);
                         

                        }
                    }
                }
                catch (Exception )
                {
                 //   myLoginModel.ErrorMsg = "not found";
                    myaction = View(myLoginModel);
                }
            }
            else
            {
                myaction = View();

            }
            return myaction;
        }
       
        [HttpGet]
      public ActionResult SignUpView()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SignUpView(Registration mymodelSignUp)

        {
            ActionResult myaction = RedirectToAction("VenderActionIndex", "Vendor");

            try
            {

                //regform.name = mymodelSignUp.name;
                //regform.email = mymodelSignUp.email;
                //regform.address = mymodelSignUp.address;
                //regform.cellNo = mymodelSignUp.cellNo
                //regform.password = mymodelSignUp.password;
                //regform.userType = mymodelSignUp.userType
                //regform.time = Convert.ToString(DateTime.Now.Date);
                //if (mymodelSignUp.userType == "Vendor")
                //{
                //    regform.isActive = false;
                //}
                //else
                //{
                //    regform.isActive = true;
                //}

                //#region Save Image on Server
               

                string FileName = Path.GetFileNameWithoutExtension(mymodelSignUp.Image_new.FileName);
                string Extension = Path.GetExtension(mymodelSignUp.Image_new.FileName);
                FileName = FileName + DateTime.Now.ToString("yymmssff") + Extension;
                mymodelSignUp.Image = "~/Pictures/" + FileName;

                FileName = Path.Combine(Server.MapPath("~/Pictures/"), FileName);

                mymodelSignUp.Image_new.SaveAs(FileName);

                db.Registrations.Add(mymodelSignUp);
                db.SaveChanges();
                myaction = RedirectToAction("VenderActionIndex", "Vendor", mymodelSignUp);
            }
            catch (Exception ex)
            {
                Response.Write(ex.Message);
               
            }


            return myaction;
        }
       
    }
}

TheBigDukan/Views/LogIn/LogInAction.cshtml
@model TheBigDukan.Registration

@{
    ViewBag.Title = "LogInAction";
}

<style>
    .login-head {
        width: 50%;
        margin: 0 auto;
        float: initial;
        margin-top: 1em;
        font-size: 6.5em;
    }
    .remove-padding {
            padding: 0;
    }
    .margin-10 {
            margin-top: 4em;
    }
    .margin-1 {
            margin-top: 1em;
    }
    .margin-0 {
            margin: 0 auto;
    }

    .dpdw{
        width: 278px;
    height: 30px;
    border-radius: 5px;
    }
    .container-new {
        background-color:blue;
    }
    [name=userType] {
        width: 278px;
    height: 30px;
    border-radius: 5px;
    }
    input[type=password] {
        display: block;
        width: 100%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.428571429;
        color: #555;
        vertical-align: middle;
        background-color: #fff;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,0.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,0.075);
        -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        margin: 0 auto;
    }
   
</style>

 <div class=" " style="margin-top: -39px;">
@using (Html.BeginForm("LogInAction","Login",FormMethod.Post))
    {
        @Html.AntiForgeryToken()
  
        <div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
   @*  <!--  <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
        <!--    <input type="submit" value="Login" class="btn btn-info" />
            <input type="button" class="btn btn-info" value="SignUp" /> -->

        </div>
    </div>-->*@

    @*@Html.DisplayFor(model => model.ErrorMsg)*@
</div>
        <div class="col-md-6" style="background:#61082b;height: 100vh;color: #fff;">
            <h1 class="login-head">
                The BIG Dukaan
            </h1>
            <p style="font-size: 2.2em;">
                Dukaan is a modern shopping experience designed to reduce your busywork so you can focus on the things that matter.
            </p>
        </div>
        <div class="col-md-6 remove-padding">
            <div class="col-md-12 margin-1">
                <div class="col-md-5 remove-padding">
                  <!--  <input id="txtUser" type="text" class="form-control" name="username" placeholder="Username">-->
                    @Html.TextBoxFor(model => model.email, new { @class = "form-control", placeholder = "Email" })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })


                </div>
                <div class="col-md-5 remove-padding">
                  <!--  <input id="passUser" type="password" class="form-control" name="password" placeholder="Password">-->
                    @Html.PasswordFor(model => model.password, new { htmlAttributes = new { @class = "form-control" }, placeholder = "Password" })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-2 ">
                    <button class="btn btn-default">Login</button>
                </div>
            </div>         
        </div>
}





@using (Html.BeginForm("SignUpView", "LogIn",FormMethod.Post, new { enctype = "multipart/form-data" }))
     {
            <div class="col-md-12 margin-10 text-center">
                <h3>
                    Join Dukaan today.
                </h3>
                <div class="form-group">
                    <label for="exampleInputEmail1">Name</label>
                    @*<input type="text" class="form-control margin-0" id="exampleInputEmail1" placeholder="Name">*@
                    @Html.EditorFor(model=>model.name, new { htmlAttributes = new { @class = "form-control margin-0", placeholder = "Name"} })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Email</label>
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new {@class = "form-control margin-0", placeholder="Email" } })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Address</label>
                    @*<input type="text" class="form-control margin-0" id="exampleInputPassword1" placeholder="Address">*@
                    @Html.EditorFor(model=>model.address, new { htmlAttributes = new { @class = "form-control margin-0", placeholder = "Address" } })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Cell #</label>
                 @*<input type="text" class="form-control margin-0" id="exampleInputPassword1" placeholder="Cell number"> *@
                    @Html.EditorFor(model=>model.cellNo, new { htmlAttributes = new { @class = "form-control margin-0", placeholder = "Cell Number" } })
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Password</label>
                    @*<input type="password" class="form-control margin-0" id="exampleInputEmail1" placeholder="Password">*@
                    @Html.PasswordFor(model => model.password, new { htmlAttributes = new { @class = "form-control" }, placeholder = "Password" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Who are you ?</label><br />
                   @* <input type="text" class="form-control margin-0" id="exampleInputPassword1" placeholder="Are you a customer ?">*@
                   @Html.DropDownListFor(model => model.userType, new List<SelectListItem> { new SelectListItem { Text = "Select", Value = "", }, new SelectListItem { Text = "Vendor", Value = "Vendor", }, new SelectListItem { Text = "Customer", Value = "Customer", } }, new { htmlAttributes = new { @class = "form-control margin-0" } })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Profile Picture</label>

                    <input type="file" name="Image_new" value="Image_new"  class="form-control margin-0"/>
                   
                <div class="form-group">
                    <button class="btn btn-default"  onclick="location.href='@Url.Action("SignUpView", "LogIn")'">Sign up</button>
                </div>
            </div>
        </div>
    }

    <div>
        @*  @Html.ActionLink("SignUp", "SignUpView") *@

    </div>
    
</div>

TheBigDukan/Views/LogIn/SignUpView.cshtml
@model TheBigDukan.Models.SignUpModel

@{
    ViewBag.Title = "SignUpView";
}
<style>
    .dpdw{
        width: 278px;
    height: 30px;
    border-radius: 5px;
    }
    .container-new {
        background-color:blue;
    }
    [name=UserType] {
        width: 278px;
    height: 30px;
    border-radius: 5px;
    }
</style>

<h2>SignUp</h2>

@using (Html.BeginForm("SignUpView","Login",FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CellNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CellNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CellNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
              
                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control"}})
               
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
              <div class="dpdw" style="background-color:forestgreen">
                  @Html.DropDownListFor(model => model.UserType, new List<SelectListItem> { new SelectListItem { Text = "Select", Value = "", }, new SelectListItem { Text = "Vendor", Value = "Vendor", }, new SelectListItem { Text = "Customer", Value = "Customer", } }, new { htmlAttributes = new { @class = "form-control" } })
              </div>        
             @Html.ValidationMessageFor(model => model.UserType, "", new { @class = "text-danger" })
            </div>
            <input   type="file" name="Image_new" value="Image_new"/>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
               
            </div>
        </div>
    </div>

}